python3Packages.torch_{2_7,2_8}: Add support for XPU (#89)
* Add support for PyTorch on XPU

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

back

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

clean

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

oneapi package fix

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

oneapi fix

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

fix dpcpp linker error

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

add pti

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

torch support

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

torch USE_XPU enabling

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

oneDnn working!

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

clean oneDNN nix

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

integrate oneDNN with torch

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

add pti

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

add xpu ops

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

debug xpu ops

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

back bintools

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

back for fix in torch_xpu

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

back for oneapi version change

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

torch 2_7_1 need oneapi 2025.0

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

add vtune for ocloc

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

onednn xpu header file

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

clean code, enable torch_2_8

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

gcc is not needed in default.nix

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

add hook

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

split ocloc, do not need install vtune

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

use oneMKL

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

remove unnecessage change in xpu ops

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

CI: show Nix information

Disable cachix uploads, we do not want to push impure builds

fix: simple transformer package

fix: nix formatter

feat: add huggingface-hub

fix: format

fix: remove maintainers in transformer module

python3Packages.torch_2_8: 2.8.0-rc8 -> 2.8.0 (#84)

* Back to `nixos-unstable-small`

* Remove `outlines` from `all`

* Set cudaPackages to cudaPackages_12_9

* python3Packages.torch_2_8: 2.8.0-rc8 -> 2.8.0

* nix fmt

torch default is 2.8 now

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

Fix all the nixpkgs update fallout (#85)

* Vendor `cuda-packages` from nixpkgs

nixpkgs has removed CUDA 11.8 and 12.0 to 12.5. However, in
kernel-builder we need:

- CUDA 11.8 for Torch 2.7.
- CUDA 12.4 for FA3 (currently errors out on newer nvcc).

So, vendor old CUDA versions, at least for the time being.

* Vendor nixpkgs gcc derivation for gcc 11 and 12

gcc11Stdenv is required for CUDA 11.8. We are using gcc12Stdenv in
kernel-builder for ROCm kernel builds.

* python3Packages.triton-rocm: 3.2.0 -> 3.4.0

Also add patches to fix the build.

* python3Packages.torch_2_7: fix Triton 2.4 compatibility

* python3Packages.torch_2_6: remove

* Scrub maintainers

We do not want to bother upstream maintainers with our vendored
packages.

* Make the xpu-packages package set more canonical Nix

- Flatten the directory structure inside output paths to have top-level
  `bin`, `include`, lib` and `share`. This makes more of the Nix
  machinery kick int.
- Define overrides to add dependencies to packages to get
  autoPatchelfHook to add proper RPATHs. Remove most library ignores.
- Remove version numbers from the package names.
- Merge `-devel` packages with main packages.
- Move icx/icpx compiler options from oneDNN-xpu to icx/icpx wrappers
  (since we always need them).
- Many smaller cleanups.

Torch does not build yet in pure builds.

* ocloc: fix dlopen'ing ocloc libraries use dpkg for unpacking

Some of the ocloc shared libraries dlopen other libraries. Add RPATH to
all shared libraries to ensure that dlopen does not fail.

* Get closer to sandboxed Torch build

Torch still does not fully build. I have to fix the sycl compiler
header handling a bit, because they continue to get picked up by g++.
Passing the special host compiler wrapper to sycl everywhere is
annoying.

* Remove hostCompiler wrapping, still issues with MKL

Seems like two versions of MKL are getting mixed:

/build/source/third_party/torch-xpu-ops/src/ATen/native/xpu/mkl/SpectralOps.cpp:73:57: error: ‘NOT_INPLACE’ is not a member of ‘oneapi::mkl::dft::config_value’
   73 |   desc.set_value(config_param::PLACEMENT, config_value::NOT_INPLACE);

* Avoid mixing two oneMKL versions

Torch 2.8 builds with this change.

* Refine `useMKL` condition

* Fix Torch 2.7 build

* Cleanups

* xpu.python3Packages: add torch_2_8 for completeness

---------

Co-authored-by: Wang, Yi A <yi.a.wang@intel.com>